SERVER_PORT_NUMBER = 5000

MONGODB_URI = 'mongodb://localhost:27017/'
DB_NAME = 'FYPServer'
RAW_SENSORY_DATA_COLLECTION = 'RawSensoryData'
ACTIVITY_HISTORY_COLLECTION = 'ActivityHistory'
ACTIVITY_RECOGNITION_QUEUE_COLLECTION = 'ActivityRecognitionQueue'