SERVER_PORT_NUMBER = 5000

MONGODB_URI = 'mongodb://localhost:27017/'
DB_NAME = 'fyp_server_db'
SP_RAW_ACCELEROMETER_DATA_COLLECTION = 'sp_raw_accelerometer'
SW_RAW_ACCELEROMETER_DATA_COLLECTION = 'sw_raw_accelerometer'
SP_RAW_GYROSCOPE_DATA_COLLECTION = 'sp_raw_gyroscope'
SW_RAW_GYROSCOPE_DATA_COLLECTION = 'sw_raw_gyroscope'
SP_RAW_BAROMETER_DATA_COLLECTION = 'sp_raw_barometer'
SW_RAW_BAROMETER_DATA_COLLECTION = 'sw_raw_barometer'
ACTIVITY_HISTORY_COLLECTION = 'activity_history'
WORK_QUEUE_COLLECTION = 'work_queue'